### ISSUE TITLE
feat(profiles): tools specific config files

### ISSUE THREAD

**Issue by ocervell** [freelabz/secator#172]
Some tools require their own configs.

In `secator`'s `config.yaml`
```yaml
...
tasks:
  dirsearch:
    config_path: /path/to/dirsearch/config.yaml  # or
    config: | # inline YAML / .ini / .conf
    config_type: YAML
```
