### ISSUE TITLE
feat: `hooks` - add hooks to certain object types

### ISSUE THREAD

**Issue by ocervell** [freelabz/secator#199]
Runtime hooks to hook up to any object of a certain output type and to run actions on it:

```yaml
#example/hooks/http_response_analyzer.yaml
type: background_task
name: http
tags: [http, pattern]
tasks:
 - ph:
   description: Analyze HTTP responses as they come through
   targets_:
   - type: url
      field: response_path
      condition: response_path != ""
workflows:
  - deobfuscate:
      targets_:
        type: url
        field: url
        condition: item.url.contains('.min.js')
```

Run workflow with hooks:
```
secator w url_crawl <target> -hooks http_response_analyzer -driver mongodb # automatically run HTTP hooks.
```
