### ISSUE TITLE
feat (core): Adding two `_group` key in the same YAML fails

### ISSUE THREAD

**Issue by ocervell** [freelabz/secator#201]
keys must be unique in YAML...
so this config won't work:

```
tasks:
 _group:
  a:
  b:
 c:
 _group:
  d:
  e:
```

will fail. We need to have `/` notation for groups:

```
tasks:
 _group/crawl:
  a:
  b:
 c:
 _group/fuzz:
  d:
  e:
```
