### ISSUE TITLE
feat: options pre-processors

### ISSUE THREAD

**Issue by ocervell** [freelabz/secator#335]
Add way to specific an option pre-processor.

For instance, for the `wordlist` argument, we could have a pre-processor that takes an URL and downloads it locally, so that:

```
secator x ffuf http://localhost:8000/FUZZ -w https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/DNS/deepmagic.com-prefixes-top500.txt
```

First downloads the wordlist and then executes `ffuf` with the local wordlist.

or by name:
```
secator x ffuf http://localhost:8000/FUZZ -w deepmagic
```

would map to the config value:
```yml
# ~/.secator/config.yml
wordlists:
  files:
    deepmagic: https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/DNS/deepmagic.com-prefixes-top500.txt
```
