### ISSUE TITLE
feat: nmap scanning too many port (port_scan workflow)

### ISSUE THREAD

**Issue by romisfrag** [freelabz/secator#421]
After a naabu scan in the "port_scan.yaml" workflow, nmap will scan all the open ports on all IP adresses
![image](https://github.com/user-attachments/assets/e654107e-53dd-4691-8395-512f76c3e646)

**Comment by ocervell** [comment]
`nmap` cannot take a combination host / port unfortunately. 

To implement this we would need to leverage the chunking mechanism already implemented in `secator` and add a feature to our workflow YAML language, which would (probably) look something like:
```yaml
  naabu:
    description: Find open ports
  nmap:
    description: Search for vulnerabilities on open ports
    chunk_by: port.host
    targets_: port.host
    ports_: port.port
```
