### ISSUE TITLE
feat: add filters DSL for results filtering

### ISSUE THREAD

**Issue by ocervell** [freelabz/secator#58]
Add filtering DSL for YAMLs (Lucene DSL ?)
```
results:
 filter:
   - type: vulnerability
      condition: (confidence:high OR confidence:medium)
```

Add ability to filter previous results with a DSL like:

```
secsy utils report show -f vulnerability.level=critical, port.host ~=*. synology.me
```

There is https://github.com/edeca/querydict for filtering lists of dicts with the Lucene query language but it doesn't support advanced language like regexes ... On the other hand doing this would help adding other backends later.
