### ISSUE TITLE
feat(config): scan / workflow / task default format options

### ISSUE THREAD

**Issue by ocervell** [freelabz/secator#62]
```yml
scan:
 format:
  print_timestamp: True
  print_cmd: True
  print_cmd_prefix: not sync
  print_table: True
```
