### ISSUE TITLE
feat(profiles): tools defaults

### ISSUE THREAD

**Issue by ocervell** [freelabz/secator#67]
Add configurable defaults to the profiles? YAML where we can configure defaults settings:

```yaml
global:
  rate_limit: 100
tasks:
  httpx:
   default_options:
     td: true
     silent: true
```
